# Generated by Django 4.1.1 on 2022-09-26 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Busines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "fulladdress",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("categories", models.CharField(blank=True, max_length=250, null=True)),
                ("phone", models.CharField(blank=True, max_length=250, null=True)),
                ("phones", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "review_count",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "average_rating",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("review_url", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "google_maps_url",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("latitude", models.CharField(blank=True, max_length=250, null=True)),
                ("longitude", models.CharField(blank=True, max_length=250, null=True)),
                ("website", models.CharField(blank=True, max_length=250, null=True)),
                ("domain", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "opening_hours",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "featured_image",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("date_added", models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
