# Generated by Django 4.1.1 on 2022-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busines",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
