# Generated by Django 4.1.1 on 2022-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0002_alter_busines_date_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="busines",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "New"),
                    (1, "Onhold"),
                    (2, "In Progress"),
                    (3, "Completed"),
                    (4, "Canceled"),
                    (5, "Rejected"),
                    (6, "Accepted"),
                    (7, "No Rsponse"),
                ],
                default=0,
            ),
        ),
    ]
