# Generated by Django 4.1.1 on 2022-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0003_busines_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busines",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
