# Generated by Django 4.1.1 on 2022-09-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0004_alter_busines_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "busines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Main.busines"
                    ),
                ),
            ],
        ),
    ]
