# Generated by Django 4.1.1 on 2022-10-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('busines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.busines')),
            ],
        ),
    ]
