# Generated by Django 4.1.1 on 2022-10-04 21:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_contact_delete_wiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
